apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE
  labels:
    app: SERVICE 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE
  template:
    metadata:
      labels:
        app: SERVICE
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - microservices-node-pool
      containers:
      - name: SERVICE
        image: greenstand/SERVICE:TAG
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: treetracker-database-connection
                key: db
          - name: DATABASE_SCHEMA
            value: messaging
