apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - database-connection-sealed-secret.yaml
  - postgrest-config.yaml
  - postgrest-deployment.yaml
  - postgrest-service.yaml
  - postgrest-ingress.yaml

