#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo "${GREEN}Checking commit message for compliance with conventional commits${NC}"
echo "${GREEN}Speficiation: https://www.conventionalcommits.org/en/v1.0.0/${NC}"
npx --no-install commitlint -H 'https://www.conventionalcommits.org/en/v1.0.0/' --edit $1
