# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI for New Pull Requests

on:
  pull_request:
    branches:
      - main
env:
  project-directory: ./
  DATABASE_URL: postgresql://postgres:postgres@postgres/postgres

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    container: node:16.12.0

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:11-2.5-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm clean install
        run: npm ci --ignore-scripts

      - name: Typescript compiles
        run: npm run build

      - name: Eslint
        run: npm run lint

      - name: install psql
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client

      - name: Prepare DB
        run: psql postgresql://postgres:postgres@postgres/postgres < db.sql

      - name: run tests
        run: npm test

      - name: run e2e tests
        run: npm run test-e2e
